global using MicronSQL.Interfaces;
global using Microsoft.AspNetCore.Mvc;
global using MicronSQL.Models;
global using MicronSQL.Managers;
global using MicronSQL.Repositories;
global using MicronSQL.WebAPI;
global using MicronSQL.Exceptions;
global using Microsoft.AspNetCore.Diagnostics;
global using System.Net;